### ISSUE TITLE
Calendar doesn't appear until app restarts

### ISSUE THREAD

**Issue by dalb8** [felixwiemuth/LinCal#4] opened 2017-03-27 10:43 UTC
I added the example calendar from primary storage (had to grant storage permission) and it didn't appear in the main activity until I opened the app the following day. 

Android 6 . stock lg g4

**Comment by felixwiemuth** [comment] 2017-08-25 16:28
Thank you for the report. I assume you refer to version 1.0.0. As far as I know the problem only occurred in special cases, at least not always, but some of the reasons why this could happen should already be fixed in 1.1.0.

However, I could reproduce this again in a version after 1.1.0, where it only occurred with "content://" file URIs. Strangely, the calendar did show up as expected when typing in the title field, even when clearing it again. For developers: I guess the reason is that in some cases the RecyclerView containing the calendar list updated on its own and in some not. This will be fixed in a future commit by always notifying the RecyclerView of added items.

In 1.2.0 the problem should be gone completely.

**Closed as completed** 2017-08-25 16:35 UTC
Labels: Bug report
